(reco) implement semi-edito pl
pass-culture/api-data pull request #164
Opened 2024-06-11 13:13 UTC by LucileRainteau

### Select PR template in preview mode:
* [Hotfix](?expand=1&template=Hotfix_template.md)
* [MES](?expand=1&template=MES_template.md)
* [MEP](?expand=1&template=MEP_template.md)
* [Other](?expand=1&template=Refacto_template.md)

2024-06-12 08:40 UTC, cdelabre commented on apps/recommendation/api/src/huggy/core/endpoint/retrieval_endpoint.py
> +            "offer_id": str(self.item_id)
Est-ce que l'on supprimera ce champ par la suite pour ne garder qu'une liste d'items ?

2024-06-12 08:44 UTC, cdelabre commented on apps/recommendation/api/src/huggy/views/home.py
> +            context="similar_offer",
Il faudrait rajouter un nouveau flag contexte (cela nous permet de différencier les différents cas de context pour le tracking)

2024-06-17 09:33 UTC, LucileRainteau commented on apps/recommendation/api/src/huggy/core/endpoint/retrieval_endpoint.py
> +            "offer_id": str(self.item_id)
Ticket de mini refacto créé pour réflechir à ce sujet :https://www.notion.so/passcultureapp/880351701699470cb129e4e0ad6bbcba?v=f77024eeaeb14713a3f1c75b31d8aa80&p=00677d90831047619680de93f84d1603&pm=s

2024-06-18 09:13 UTC, dcuesta-pass commented on apps/recommendation/api/src/huggy/core/model_engine/similar_offer.py
> +        if len(self.offers) > 0 and len([offer.item_id for offer in self.offers]) == 0:
Logique OK à voir si on garde

2024-06-18 09:49 UTC, cdelabre commented on apps/recommendation/api/src/huggy/core/endpoint/retrieval_endpoint.py
> +            "offer_id": str(self.item_id)
+1

2024-06-24 12:43 UTC, LucileRainteau commented on apps/recommendation/api/src/huggy/views/home.py
> +    if offers:
Le use case est une génération de playlist sur la home, ça me parait ok de le laisser ici pour le moment, mais on peut en rediscuter :)

2024-06-24 16:07 UTC, cdelabre commented on apps/recommendation/api/src/huggy/views/home.py
> +    if offers:
Oui

2024-06-24 16:09 UTC, cdelabre requested changes

2024-06-24 16:09 UTC, cdelabre commented on apps/recommendation/api/src/huggy/views/home.py
> +            context="pl_semi_edito",
semi-editorial

2024-06-25 10:33 UTC, dcuesta-pass commented on apps/recommendation/api/src/huggy/core/endpoint/retrieval_endpoint.py
> +        if params_in.offers:
params_in.offers est toujours définis non ? Vu quand dans le __init__.py , tu le définis quoiqu'il arrive

2024-06-25 10:33 UTC, dcuesta-pass commented on apps/recommendation/api/src/huggy/core/model_engine/__init__.py
> +        self.offers = (
Ici

2024-06-25 13:03 UTC, dcuesta-pass approved these changes

2024-06-25 13:50 UTC, merged